#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World  inside

sudo apt-get update -y && \
sudo apt-get install -y nginx
sudo echo "Hello World!" >> /var/www/html/index.html
