#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World  inside

sudo apt-get update -y && \
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!\n" | sudo tee /var/www/html/index.html
sudo service nginx restart
